### ISSUE TITLE
Hard dependency on outdated version of BoP...

### ISSUE THREAD

**Issue by ate0ate** [undertrox/boptools#1]
Looks like an excellent mod, but it seems to have a dependency on BoP 7.0.1.2314 while the newest version is significantly ahead at 7.0.1.2334.

**Comment by undertrox** [comment]
Fixed in [v0.0.2.1](https://github.com/undertrox/boptools/releases/tag/v0.0.2.1)

**Comment by ate0ate** [comment]
Awesome! That was very fast. Thank you so much for your work on the mod. Excellent little quality of life improvement.
